// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi0GDJANT36iV2mwR1jneizNGF8tNA2R8',
    appId: '1:231537215932:web:fabcbbdbcdaefe4b4683b9',
    messagingSenderId: '231537215932',
    projectId: 'ecommerce-app-58f2c',
    authDomain: 'ecommerce-app-58f2c.firebaseapp.com',
    storageBucket: 'ecommerce-app-58f2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwwjzzan6ScAwrdfPqfcCRdzawVjle4oE',
    appId: '1:231537215932:android:b66be127c550351c4683b9',
    messagingSenderId: '231537215932',
    projectId: 'ecommerce-app-58f2c',
    storageBucket: 'ecommerce-app-58f2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN8yjyJb1bIUaxFd8alSpT-0YtmmNrid4',
    appId: '1:231537215932:ios:ad494c7b3942b1bb4683b9',
    messagingSenderId: '231537215932',
    projectId: 'ecommerce-app-58f2c',
    storageBucket: 'ecommerce-app-58f2c.appspot.com',
    iosClientId: '231537215932-7otkpcqd16lliqdm7v8i5qfacpkjqnhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.api',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN8yjyJb1bIUaxFd8alSpT-0YtmmNrid4',
    appId: '1:231537215932:ios:8c01f113c01beedb4683b9',
    messagingSenderId: '231537215932',
    projectId: 'ecommerce-app-58f2c',
    storageBucket: 'ecommerce-app-58f2c.appspot.com',
    iosClientId: '231537215932-hkq09scp27g3ag7e187574nmb24k3hji.apps.googleusercontent.com',
    iosBundleId: 'com.example.api.RunnerTests',
  );
}
